### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wemanzoz** [TcNobo/TcNo-Acc-Switcher#21]
02/11/2021 14:03:37	UNHANDLED CRASH: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Steam\config\loginusers.vdf'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at TcNo_Acc_Switcher_Steam.MainWindow.GetSteamAccounts() in C:\Users\TechNobo\Documents\GitHub\TCNO-Acc-Switcher\TcNo-Account-Switcher\TcNo-Acc-Switcher_Steam\MainWindow.xaml.cs:line 405
   at TcNo_Acc_Switcher_Steam.MainWindow.RefreshSteamAccounts() in C:\Users\TechNobo\Documents\GitHub\TCNO-Acc-Switcher\TcNo-Account-Switcher\TcNo-Acc-Switcher_Steam\MainWindow.xaml.cs:line 100
   at TcNo_Acc_Switcher_Steam.MainWindow..ctor(Boolean argumentLaunch) in C:\Users\TechNobo\Documents\GitHub\TCNO-Acc-Switcher\TcNo-Account-Switcher\TcNo-Acc-Switcher_Steam\MainWindow.xaml.cs:line 85
   at TcNo_Acc_Switcher_Steam.App.OnStartup(StartupEventArgs e) in C:\Users\TechNobo\Documents\GitHub\TCNO-Acc-Switcher\TcNo-Account-Switcher\TcNo-Acc-Switcher_Steam\App.xaml.cs:line 26
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TcNo_Acc_Switcher_Steam.App.Main()

**Comment by TcNobo** [comment]
This is most commonly caused by Steam being installed in a different location, or the file is inaccessible due to Windows settings or an Anti Virus protecting your files.

1. Verify that this file exists (or doesn't), and you have access to open it in something like Notepad: `C:\Program Files (x86)\Steam\config\loginusers.vdf`

Steam installed in a different location? Open TcNo Account Switcher, click the Settings icon in the bottom right, then "Pick Steam folder" under General.
Unable to open the program at all? Navigate to the installation folder. (Simply Right-Click a shortcut and Open File Location -- Default install is: `C:\Program Files\TcNo Account Switcher`). Open the Steam subfolder and delete `SteamSettings.json`. This will reset the program's settings. Next launch should ask you to locate Steam.

**Comment by TcNobo** [comment]
Assuming this was solved.

**Comment by wemanzoz** [comment]
it was solved thanks

**Comment by AirAustin** [comment]
The manager still keeps saying it couldn't locate "loginusers.vdf". After reinstalling the program, deleting the file and making a new one, locating steam folder, everything. The manager still says "Failed to load steam/config/loginusers.vdf"

**Comment by Skripterr** [comment]
The app is completely broken
